package entities;
// Generated 14-nov-2017 11:46:19 by Hibernate Tools 5.2.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Evento generated by hbm2java
 */
@Entity
@Table(name = "Evento", catalog = "mytokyo2020")
public class Evento implements java.io.Serializable {

	private int idEvento;
	private Disciplina disciplina;
	private String lugar;
	private Date fecha;
	private Date hora;
	private String tipo;
	private String resultados;
	private Date lastModification;
	private Set<UsuarioCompraEvento> usuarioCompraEventos = new HashSet<UsuarioCompraEvento>(0);
	private Set<EventoParticipaDeportista> eventoParticipaDeportistas = new HashSet<EventoParticipaDeportista>(0);

	public Evento() {
	}

	public Evento(int idEvento, Disciplina disciplina, Date lastModification) {
		this.idEvento = idEvento;
		this.disciplina = disciplina;
		this.lastModification = lastModification;
	}

	public Evento(int idEvento, Disciplina disciplina, String lugar, Date fecha, Date hora, String tipo,
			String resultados, Date lastModification, Set<UsuarioCompraEvento> usuarioCompraEventos,
			Set<EventoParticipaDeportista> eventoParticipaDeportistas) {
		this.idEvento = idEvento;
		this.disciplina = disciplina;
		this.lugar = lugar;
		this.fecha = fecha;
		this.hora = hora;
		this.tipo = tipo;
		this.resultados = resultados;
		this.lastModification = lastModification;
		this.usuarioCompraEventos = usuarioCompraEventos;
		this.eventoParticipaDeportistas = eventoParticipaDeportistas;
	}

	@Id

	@Column(name = "idEvento", unique = true, nullable = false)
	public int getIdEvento() {
		return this.idEvento;
	}

	public void setIdEvento(int idEvento) {
		this.idEvento = idEvento;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Disciplina_idDisciplina", nullable = false)
	public Disciplina getDisciplina() {
		return this.disciplina;
	}

	public void setDisciplina(Disciplina disciplina) {
		this.disciplina = disciplina;
	}

	@Column(name = "Lugar", length = 45)
	public String getLugar() {
		return this.lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Fecha", length = 0)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "Hora", length = 0)
	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	@Column(name = "Tipo", length = 45)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "Resultados", length = 45)
	public String getResultados() {
		return this.resultados;
	}

	public void setResultados(String resultados) {
		this.resultados = resultados;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModification", nullable = false, length = 0)
	public Date getLastModification() {
		return this.lastModification;
	}

	public void setLastModification(Date lastModification) {
		this.lastModification = lastModification;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "evento")
	public Set<UsuarioCompraEvento> getUsuarioCompraEventos() {
		return this.usuarioCompraEventos;
	}

	public void setUsuarioCompraEventos(Set<UsuarioCompraEvento> usuarioCompraEventos) {
		this.usuarioCompraEventos = usuarioCompraEventos;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "evento")
	public Set<EventoParticipaDeportista> getEventoParticipaDeportistas() {
		return this.eventoParticipaDeportistas;
	}

	public void setEventoParticipaDeportistas(Set<EventoParticipaDeportista> eventoParticipaDeportistas) {
		this.eventoParticipaDeportistas = eventoParticipaDeportistas;
	}

}
