package entities;
// Generated 14-nov-2017 0:06:16 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsuarioCompraEventoId generated by hbm2java
 */
@Embeddable
public class UsuarioCompraEventoId implements java.io.Serializable {

	private String usuarioUsername;
	private int eventoIdEvento;

	public UsuarioCompraEventoId() {
	}

	public UsuarioCompraEventoId(String usuarioUsername, int eventoIdEvento) {
		this.usuarioUsername = usuarioUsername;
		this.eventoIdEvento = eventoIdEvento;
	}

	@Column(name = "Usuario_Username", nullable = false, length = 10)
	public String getUsuarioUsername() {
		return this.usuarioUsername;
	}

	public void setUsuarioUsername(String usuarioUsername) {
		this.usuarioUsername = usuarioUsername;
	}

	@Column(name = "Evento_idEvento", nullable = false)
	public int getEventoIdEvento() {
		return this.eventoIdEvento;
	}

	public void setEventoIdEvento(int eventoIdEvento) {
		this.eventoIdEvento = eventoIdEvento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioCompraEventoId))
			return false;
		UsuarioCompraEventoId castOther = (UsuarioCompraEventoId) other;

		return ((this.getUsuarioUsername() == castOther.getUsuarioUsername())
				|| (this.getUsuarioUsername() != null && castOther.getUsuarioUsername() != null
						&& this.getUsuarioUsername().equals(castOther.getUsuarioUsername())))
				&& (this.getEventoIdEvento() == castOther.getEventoIdEvento());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUsuarioUsername() == null ? 0 : this.getUsuarioUsername().hashCode());
		result = 37 * result + this.getEventoIdEvento();
		return result;
	}

}
