package entities;
// Generated 23-nov-2017 20:02:51 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsuarioCompraEventoId generated by hbm2java
 */
@Embeddable
public class UsuarioCompraEventoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4548523488867411835L;
	private String usuarioEmail;
	private int eventoIdEvento;

	public UsuarioCompraEventoId() {
	}

	public UsuarioCompraEventoId(String usuarioEmail, int eventoIdEvento) {
		this.usuarioEmail = usuarioEmail;
		this.eventoIdEvento = eventoIdEvento;
	}

	@Column(name = "Usuario_Email", nullable = false, length = 50)
	public String getUsuarioEmail() {
		return this.usuarioEmail;
	}

	public void setUsuarioEmail(String usuarioEmail) {
		this.usuarioEmail = usuarioEmail;
	}

	@Column(name = "Evento_idEvento", nullable = false)
	public int getEventoIdEvento() {
		return this.eventoIdEvento;
	}

	public void setEventoIdEvento(int eventoIdEvento) {
		this.eventoIdEvento = eventoIdEvento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioCompraEventoId))
			return false;
		UsuarioCompraEventoId castOther = (UsuarioCompraEventoId) other;

		return ((this.getUsuarioEmail() == castOther.getUsuarioEmail()) || (this.getUsuarioEmail() != null
				&& castOther.getUsuarioEmail() != null && this.getUsuarioEmail().equals(castOther.getUsuarioEmail())))
				&& (this.getEventoIdEvento() == castOther.getEventoIdEvento());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUsuarioEmail() == null ? 0 : this.getUsuarioEmail().hashCode());
		result = 37 * result + this.getEventoIdEvento();
		return result;
	}

}
